version: "2.4"

services:
  # ---------------- BASE DE DONNEES ---------------- #
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblio_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - biblio-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8090:8080"
    depends_on:
      - mysqldb
    networks:
      - biblio-network

  # ---------------- MESSAGERIE (KAFKA) ---------------- #
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - biblio-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - biblio-network
    healthcheck:
      test: ["CMD", "kafka-topics", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 5

  # ---------------- MICROSERVICES ---------------- #

  eureka-server:
    build: ./eurika
    container_name: eureka-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=eureka-service
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx256m
    networks:
      - biblio-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 30s

  gateway-service:
    build: ./gateway
    container_name: gateway-service
    ports:
      - "9999:9999"
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - SPRING_APPLICATION_NAME=gateway-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx256m
    networks:
      - biblio-network

  user-service:
    build: ./user
    container_name: user-service
    ports:
      - "8082:8082"
    depends_on:
      eureka-server:
        condition: service_healthy
      mysqldb:
        condition: service_healthy
    environment:
      - SPRING_APPLICATION_NAME=user-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/user_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
    networks:
      - biblio-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  book-service:
    build: ./book
    container_name: book-service
    ports:
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_healthy
      mysqldb:
        condition: service_healthy
    environment:
      - SPRING_APPLICATION_NAME=book-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/book_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
    networks:
      - biblio-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  emprunt-service:
    build: ./emprunter
    container_name: emprunt-service
    ports:
      - "8085:8085"
    depends_on:
      eureka-server:
        condition: service_healthy
      mysqldb:
        condition: service_healthy
      user-service:
        condition: service_healthy
      book-service:
        condition: service_healthy
    environment:
      - SPRING_APPLICATION_NAME=emprunt-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/emprunt_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    networks:
      - biblio-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8084:8084"
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      - SPRING_APPLICATION_NAME=notification-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_KAFKA_CONSUMER_GROUP_ID=notification-group
    networks:
      - biblio-network

networks:
  biblio-network:
    driver: bridge

volumes:
  mysql_data: